/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package basics;
import java.util.concurrent.TimeUnit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
public class Main {
    public static void main(String[] args) {
        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");

        flipNHeads(4);
        clock();
    }

    public static String pluralize(String animal, int number) {
        if (number == 0 || number > 1) {
            return animal + "s";
        } else
            return animal;
    }
//f
    // coin flip
    public static void flipNHeads(int n) {
        int headCount = 0;
        int flips = 0;
        while (headCount < n) {
            flips++;
            if ((Math.random() * 1) >= 0.5) {
                headCount++;
                System.out.println("heads");

            } else if ((Math.random() * 1) < 0.5) {
                System.out.println("tails");
                headCount = 0;
            }
        }
        System.out.println("It took " + flips + " flips to flip " + n + " heads  in  a row");
    }

    // line clock
    public static void clock() {
        while (true) {
            LocalDateTime now = LocalDateTime.now();
            int h = now.getHour();
            int m = now.getMinute();
            int s = now.getSecond();
            String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            try {
                TimeUnit.SECONDS.sleep(1);

            } catch (Exception e){}
            System.out.println(time);
        }
    }
}
