/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;
public class Library {


    public static void main(String[] args) {

        roll(4);
        ContainsDuplicates();


    }

    public static int[] roll(int n) {
        //create the resulting array
        int[] result = new int[n];

        //get random numbers
        Random rand = new Random();

        //populate the array
        for (int i = 0; i < n; i++) {
            result[i] = rand.nextInt(6) + 1;
        }

        //return the array
        return result;
    }

    public static boolean ContainsDuplicates() {
        //iterate through the list
        int[] arr = roll(4);
        for (int i = 0; i < arr.length; i++) {
            //check if it's in the array already
            for (int j = i + 1; j < arr.length; j++) {
                //if it's in there return false
                if (arr[i] == arr[j]) {
                    return true;
                }
            }


        }
        return false;
    }

//

    public static double calculatedAverage(int[] nums) {
        double total = 0;
        for (int i = 0; i < nums.length; i++) {
            total = +total + nums[i];

        }
//        System.out.println(total);
        double average = total / nums.length;
//        System.out.println(average);
        return average;
    }

    public static double arrayOfArray(int[][] arrayOfArrays) {
        double lowestAvg = 1000;
        for (int i = 0; i < arrayOfArrays.length; i++) {
            double tempAvg = calculatedAverage(arrayOfArrays[i]);
            System.out.println("this is the average " + tempAvg);
            if (tempAvg < lowestAvg) {
                lowestAvg = tempAvg;
            }
            System.out.println("this is the lowest average " + lowestAvg);
        }
        return lowestAvg;
    }
}