/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {

        Restaurant test = new Restaurant("dodo","5");

        test.addReview("gg","ff",5);
        System.out.println("dddd");
        return true;
    }

}
