/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();

    }
}
